# Generated by Django 3.0.5 on 2020-05-10 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.IntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'non-binary'), (3, 'two-spirit'), (4, 'prefer not to disclose')], null=True)),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('password_expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('website_url', models.CharField(max_length=256)),
                ('logo_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('license_plate', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexually_inappropriate', models.BooleanField(default=False)),
                ('racially_inappropriate', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('nps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kavi.Platform')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavi.ServiceProvider')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavi.Customer')),
            ],
        ),
    ]
