# Generated by Django 3.0.5 on 2020-04-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('website_url', models.CharField(max_length=256)),
                ('logo_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'prefer not to disclose')])),
                ('phone_number', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('license_plate', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexually_inappropriate', models.BooleanField(default=False)),
                ('racially_inappropriate', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kavi.Platform')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavi.ServiceProvider')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavi.User')),
            ],
        ),
    ]
