# Generated by Django 3.0.5 on 2020-04-12 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kavi', '0002_auto_20200412_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nps',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
